#!/usr/bin/make -f
#drives the addId3tags.pl script
#finds all *.m4a files in dir
#Extract metadata
#Added ydtl for youtube based files
.PHONY: echotargets clean reallyclean ydtl clean
#youtube-dl binary
ytbin:=./youtube-dl
files := $(basename $(shell ls *.m4a))
#For youtbe files, no m4a, tag file needs to be generated by hand, input files is mp3
#files := $(basename $(shell ls *.mp3))
targets := $(foreach file,$(files), $(file).mp3 $(file).tag $(file).jpg $(file).chk)
all: $(targets)
echotargets:
	@echo $(files)
	@echo $(targets)
%.mp3: %.m4a
	avconv -i $< -vn -acodec libmp3lame -ac 2 -ab 128k -y $@
%.tag: %.m4a
	AtomicParsley $< -t > $@
	sed -i  's/^Atom "\(....\)" contains: /\1/' $@
%.jpg: %.m4a
	AtomicParsley $< -E
	mv $*_artwork_1.jpg $@
%.chk: %.mp3 %.tag %.jpg
	./addId3tags.pl $*
	touch $@
clean:
	rm -f *.jpg *.tag *.chk
reallyclean: clean
	rm -f *.mp3
ytdl:
	$(ytbin) -o "%(title)s.%(ext)s" -x --audio-format mp3 -a list --write-thumbnail
test:
	@echo $(targets)
